export const activityDetails = [
  {
    id: 1,
    name: "NEW GARDENS PRIMARY",
    region: "Eastern Cape",
    city: "Stutterheim",
    date: "2025-05-29",
    time: "11:30 AM",
    activities: ["School Sampling", "Lunch Box Check"],
    assigned: 1,
    completed: 0,
  },
  {
    id: 2,
    name: "NDAKANA PRIMARY SCHOOL",
    region: "Eastern Cape",
    city: "Stutterheim",
    date: "2025-05-29",
    time: "11:30 AM",
    activities: ["School Sampling", "Lunch Box Check"],
    assigned: 1,
    completed: 0,
  },
  {
    id: 3,
    name: "UMTHATHA COMMUNITY PRIMARY SCHOOL",
    region: "Eastern Cape",
    city: "Umthatha",
    date: "2025-05-28",
    time: "11:30 AM",
    activities: ["School Sampling", "Lunch Box Check"],
    assigned: 1,
    completed: 0,
  },
  {
    id: 4,
    name: "DURBAN CENTRAL PRIMARY",
    region: "KwaZulu-Natal",
    city: "Durban",
    date: "2025-06-07",
    time: "10:00 AM",
    activities: ["Health Survey", "Lunch Box Check"],
    assigned: 2,
    completed: 1,
  },
];
